# Generated by Django 4.1.5 on 2023-01-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
